
# ------------------------------ Security ENDPOINTS------------------------------
### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


### ------------   Meals API   ------------

GET {{url}}/meals

###

GET {{url}}/meals/1

###

POST {{url}}/meals
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "mealName": "Butter Chicken",
  "mealDescription": "Indian/Pakistani",
  "mealInstructions": "Instruction to cook: ......",
  "mealPrepTime": 30,
  "mealRating": 4.9
}

###

PUT {{url}}/meals/7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "mealName": "Butter Chicken UPDATED2",
  "mealDescription": "Indian/Pakistani UPDATED2"
}

###

GET {{url}}/meals/prepTime/30

###

DELETE {{url}}/meals/5


### --------------------  Ingredients ENDPOINTS  ------------------------------

POST http://localhost:7007/api/ingredients
Content-Type: application/json

{
  "name": "Salt",
  "quantity": "Some salt"
}

###

GET http://localhost:7007/api/ingredients/1

###

GET http://localhost:7007/api/ingredients

###

PUT http://localhost:7007/api/ingredients/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Pepper",
  "quantity": "0,5 cups"
}

###

DELETE http://localhost:7007/api/ingredients/1
